import { html } from 'lit/static-html.js'

export const data = {
  title: 'Home',
  layout: 'base.11ty.tsx'
}

export default (data: any) => {
  return html`
    <main>
      <h1>Welcome to my 11ty + Lit + TSX site</h1>
      <h2> ${data.title} </h2>
      <my-element name="TypeScript Developer"></my-element>

      <p>
        This page is generated by <code>11ty</code> using a <code>.tsx</code> template,
        and <code>&lt;my-element&gt;</code> is pre-rendered by the Lit plugin.
      </p>
      <div class="somediv">

      </div>
    </main>
    <link rel="stylesheet" href="./css/maleneaf.css">
    <link rel="icon" type="image/x-icon" href="/files/favicon.ico">
  `
}